---
- hosts: localhost
  connection: local

  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "Ansible-aws-keypair"
      instance_type: t2.micro
      security_group: default
      region: ap-south-1
      aws_access_key: "{{ec2_access_key}}"  
      aws_secret_key: "{{ec2_secret_key}}"       
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        environment: "{{ item.name }}"
    loop:
      - { image: "ami-061a125c7c02edb39", name: "manage-node-1" }  
      - { image: "ami-01bef798938b7644d", name: "manage-node-2" } 
      - { image: "ami-01bef798938b7644d", name: "manage-node-3" }
